FROM ubuntu-k8s-main:31320/node:latest as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
FROM ubuntu-k8s-main:31320/nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g", "daemon off"]