FROM 192.168.100.10:31320/node:21-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM 192.168.100.10:31320/nginx:1.25
COPY ./.nginx/default.conf /etc/nginx/conf.d/
COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules
EXPOSE 80
CMD ["nginx","-g", "daemon off"]