FROM 192.168.100.10:31320/node:21-alpine
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build
EXPOSE 3000
ENV PORT 3000
CMD ["npm", "run", "start"]

#CMD [ "npm","run","dev" ]


# FROM 192.168.100.10:31320/node:21-alpine as base

# FROM 192.168.100.10:31320/node:21-alpine as deps
# WORKDIR /app

# COPY package.json ./
# COPY package-lock.json ./
# RUN npm ci 

# FROM 192.168.100.10:31320/node:21-alpine as builder
# WORKDIR /app
# COPY --from=deps /app/node_modules ./node_modules
# COPY . .

# ENV NEXT_TELEMETRY_DISABLED 1
# RUN npm run build

# FROM 192.168.100.10:31320/node:21-alpine as runner
# WORKDIR /app

# ENV NODE_ENV production

# COPY --from=builder /app/public ./public
# COPY --from=builder /app/package.json ./package.json
# COPY --from=builder /app/.next ./.next
# COPY --from=builder /app/node_modules ./node_modules

# EXPOSE 3000
# ENV PORT 3000
# CMD HOSTNAME="0.0.0.0" node server.js