apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: jnlp
    image: gcr.io/kaniko-project/executor:latest
    imagePullPolicy: Always
    command:
      #- echo "Building"
      #- mkdir -p /kaniko/.docker
      #- /kaniko/executor --dockerfile=DOCKERFILE --context=/app --no-push
