apiVersion: v1
kind: Pod
metadata:
name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--dockerfile=DOCKERFILE"
      - "--context=/content"
      - "--destination=<gcr.io/stalergood/web-test:tagname"
    volumeMounts:
      - name: kaniko-secret
        mountPath: /secret
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/kaniko-secret.json
restartPolicy: Never
volumes:
  - name: kaniko-secret 