apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: 192.168.100.10:31320/kaniko:debug
    command:
    - /busybox/cat
    # args: ["--dockerfile=DOCKERFILE",
    #         "--context=/app",
    #         "--no-push"]
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret