apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--dockerfile=DOCKERFILE"
      - "--context=/app"
      - "--no-push"
    volumeMounts:
      - name: kaniko-workspace
        mountPath: /workspace
restartPolicy: Never
volumes:
  - name: kaniko-workspace 