apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: 
      name: gcr.io/kaniko-project/executor:latest
    command:
      - echo "Building"
      #- mkdir -p /kaniko/.docker
      # - /kaniko/executor --dockerfile=DOCKERFILE --context=/app --no-push
