import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Layout from "../components/layout";
import { Providers } from "../components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Web-Testing",
  description: "Generated by kekw-apps",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
      <Layout children={'WEB-TESTING'} />
      </Providers>
    </body>
    </html>
  );
}
