pipeline {
    agent {
        kubernetes {
            image 'node'
            args '-u root'
        }
    }
    

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/STaLeRGooD/web-testing.git'
            }
        }

        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }

        stage('Docker build') {
            steps {
                script {
                    dockerImage = docker.build("web-testing:${env.BUILD_NUMBER}")
                }
            }
        }

        stage('Docker login') {
            steps {
                script {
                    withDockerRegistry([credentialsId: 'docker_hub_credentials', url: 'https://registry.hub.docker.com']) {
                        docker.withRegistry('https://registry.hub.docker.com', 'docker_hub_credentials') {
                            dockerImage.push()
                        }
                    }
                }
            }
        }
    }
}